### ISSUE TITLE
Other networks?

### ISSUE THREAD

**Issue by JeremyRand** [gombadi/dnsseeder#3]
Would PR's be accepted that add config files for networks other than Bitcoin and Twister?  (I'm considering sending in a PR that adds Namecoin.)

**Comment by gombadi** [comment]
Hi
Yes happy to accept PR's for new networks.

**Comment by JeremyRand** [comment]
Great.  I think @jonasbits may be planning to send in a Namecoin PR.

**Comment by Mitchellpkt** [comment]
We might add a Zcash configuration as well. :- )

**Comment by JeremyRand** [comment]
Question is answered, and Namecoin was merged a while ago.  Closing.
